name = "web-attendance"
compatibility_date = "2024-03-20"


[[d1_databases]]
binding = "DB"
database_name = "web-attendance-db"
database_id = "eec9a750-a720-4bd6-86ea-b54995c2b78e"
preview_database_id = "DB"

[[env.production.d1_databases]]
binding = "DB"
database_name = "web-attendance-db"
database_id = "eec9a750-a720-4bd6-86ea-b54995c2b78e"

[vars]
# Use .dev.vars for local development
# Use 'wrangler pages secret put ADMIN_PASSWORD' for production
