export const QUERY_KEYS = {
    staffs: ['staffs'],
    roles: ['roles'],
    classes: ['classes'],
    shifts: (monthStr: string) => ['shifts', monthStr],
    shiftSnapshots: (monthStr: string) => ['shiftSnapshots', monthStr],
    timePatterns: ['timePatterns'],
    holidays: (year: number) => ['holidays', year],
    businessDayOverrides: (yearMonth: string) => ['businessDayOverrides', yearMonth],
    preferences: (monthStr: string) => ['preferences', monthStr],
    shiftRequirements: ['shiftRequirements'],
    shiftRequirementTemplates: ['shiftRequirementTemplates'],
    fixedDates: (monthStr: string) => ['fixedDates', monthStr],
    businessHours: ['businessHours'],
    facilityName: ['facilityName'],
    excelSettings: ['excelSettings'],
    schedulePreferences: ['schedulePreferences'],
    rotationSettings: ['rotationSettings'],
    breakSettings: ['breakSettings'],
    auditLogs: (yearMonth: string, action: string) => ['auditLogs', yearMonth, action],
};
